name: wean_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

# All development and debug version should be end after third dot. for ex(1.0.1).
# All major and master version release should be mid and first digit. for ex(1.1.0 or 2.0.0)

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase Flutter SDK
  firebase_core: ^1.8.0
  firebase_analytics: ^8.3.4
  cloud_firestore: ^2.5.4
  firebase_auth: ^3.1.4
  firebase_storage: ^10.0.6
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  otp_screen: ^0.0.3
  pinput: ^1.2.0
  intl: ^0.17.0
  flutter_image_slider: ^0.0.2
  images_picker: ^1.2.4
  timeago: ^3.1.0
  flutter_bloc: ^7.3.0
  geolocator: ^7.7.1
  geocoding: ^2.0.0
  flutter_svg: ^0.22.0
  url_launcher: ^6.0.9
  equatable: ^2.0.3
  flutter_easyloading: ^3.0.0
  image_picker: ^0.8.3+2
  file_picker: ^4.0.0
  video_thumbnail: ^0.4.3
  path_provider: ^2.0.2
  shared_preferences: ^2.0.7
  flutter_rating_bar: ^4.0.0
  firebase_messaging: ^10.0.6
  flutter_chat_types: ^3.0.1
  group_button: ^3.1.0
  package_info_plus: ^1.0.6
  country_code_picker: ^2.0.2
  faker_dart: ^0.1.2
  photo_gallery: ^1.0.1
  infinite_scroll_pagination: ^3.1.0
  uuid: ^3.0.4
  google_fonts: ^2.1.0
  location: ^4.2.0 #ios
  geocode: ^1.0.1
  google_maps_flutter: ^2.0.8
  visibility_detector: ^0.2.0
  permission_handler: ^8.1.6
  photo_view: ^0.12.0
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.1.0
  sentry_flutter: ^6.0.1
  firebase_crashlytics: ^2.2.4
  flutter_image_compress: ^1.1.0
  flutter_local_notifications: ^9.0.0
  get_it: ^7.2.0
  easy_localization: ^3.0.0
  camera: 0.8.1+7
  flutter_lints: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.1


flutter_icons:
  android: true
  ios: true
  image_path: 'assets/waen_newlogo.png'
  adaptive_icon_background: '#4f10cc'
  adaptive_icon_forground: 'assets/waen_newlogo.png'

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/svg/
    - assets/translations/

  fonts:
    - family: calibri_bold
      fonts:
        - asset: assets/fonts/calibri_bold.ttf
    - family: calibri_bold_italic
      fonts:
        - asset: assets/fonts/calibri_bold_italic.ttf
    - family: calibri_regular
      fonts:
        - asset: assets/fonts/calibri_regular.ttf
    - family: harlow
      fonts:
        - asset: assets/fonts/harlow_solid_italic.ttf
    - family: avenir
      fonts:
        - asset: assets/fonts/avenir_next_font.ttf
